version: "2"
services:
  backend:
    build: .
    image: app
    environment:
      - DATASOURCES_DEFAULT_URL=jdbc:postgresql://db:5432/root
      - DATASOURCES_DEFAULT_USERNAME=root
      - DATASOURCES_DEFAULT_PASSWORD=postgres
    ports: 
    - "8080:8080"
    depends_on:
     db:
        condition: service_healthy


  db:
    image: postgres
    environment:
      - POSTGRES_DB=root
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
    volumes:
      - test-postgres-data:/var/lib/postgres
    ports:
    - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 5s
      timeout: 5s
      retries: 5

    

volumes:
  test-postgres-data: