#Sat Aug 24 06:15:27 UTC 2024
micronaut:
  application:
    name: 'kotlin_test'

jpa:
  default:
    properties:
      hibernate:
        show-sql: true
        hbm2ddl:
          auto: update
        connection:
          db-type: postgres
        bytecode:
          provider: none
    entity-scan:
      packages: 'com.sc41ar.domains'

test-resources:
  containers:
    mariadb:
      image-name: postgres



